Add ghc 9.12, drop 9.2 from CI (#26)

diff --git a/.github/workflows/haskell-ci.yml b/.github/workflows/haskell-ci.yml
--- a/.github/workflows/haskell-ci.yml
+++ b/.github/workflows/haskell-ci.yml
@@ -8,9 +8,9 @@
 #
 # For more information, see https://github.com/haskell-CI/haskell-ci
 #
-# version: 0.19.20241121
+# version: 0.19.20250506
 #
-# REGENDATA ("0.19.20241121",["github","cabal.project"])
+# REGENDATA ("0.19.20250506",["github","cabal.project"])
 #
 name: Haskell-CI
 on:
@@ -19,7 +19,7 @@ on:
 jobs:
   linux:
     name: Haskell-CI - Linux - ${{ matrix.compiler }}
-    runs-on: ubuntu-20.04
+    runs-on: ubuntu-24.04
     timeout-minutes:
       60
     container:
@@ -28,29 +28,29 @@ jobs:
     strategy:
       matrix:
         include:
-          - compiler: ghc-9.10.1
+          - compiler: ghc-9.12.2
             compilerKind: ghc
-            compilerVersion: 9.10.1
+            compilerVersion: 9.12.2
             setup-method: ghcup
             allow-failure: false
-          - compiler: ghc-9.8.2
+          - compiler: ghc-9.10.2
             compilerKind: ghc
-            compilerVersion: 9.8.2
+            compilerVersion: 9.10.2
             setup-method: ghcup
             allow-failure: false
-          - compiler: ghc-9.6.6
+          - compiler: ghc-9.8.4
             compilerKind: ghc
-            compilerVersion: 9.6.6
+            compilerVersion: 9.8.4
+            setup-method: ghcup
+            allow-failure: false
+          - compiler: ghc-9.6.7
+            compilerKind: ghc
+            compilerVersion: 9.6.7
             setup-method: ghcup
             allow-failure: false
           - compiler: ghc-9.4.8
             compilerKind: ghc
             compilerVersion: 9.4.8
-            setup-method: ghcup
-            allow-failure: false
-          - compiler: ghc-9.2.8
-            compilerKind: ghc
-            compilerVersion: 9.2.8
             setup-method: ghcup
             allow-failure: false
       fail-fast: false
@@ -63,12 +63,12 @@ jobs:
       - name: Install GHCup
         run: |
           mkdir -p "$HOME/.ghcup/bin"
-          curl -sL https://downloads.haskell.org/ghcup/0.1.30.0/x86_64-linux-ghcup-0.1.30.0 > "$HOME/.ghcup/bin/ghcup"
+          curl -sL https://downloads.haskell.org/ghcup/0.1.50.1/x86_64-linux-ghcup-0.1.50.1 > "$HOME/.ghcup/bin/ghcup"
           chmod a+x "$HOME/.ghcup/bin/ghcup"
       - name: Install cabal-install
         run: |
-          "$HOME/.ghcup/bin/ghcup" install cabal 3.12.1.0 || (cat "$HOME"/.ghcup/logs/*.* && false)
-          echo "CABAL=$HOME/.ghcup/bin/cabal-3.12.1.0 -vnormal+nowrap" >> "$GITHUB_ENV"
+          "$HOME/.ghcup/bin/ghcup" install cabal 3.14.2.0 || (cat "$HOME"/.ghcup/logs/*.* && false)
+          echo "CABAL=$HOME/.ghcup/bin/cabal-3.14.2.0 -vnormal+nowrap" >> "$GITHUB_ENV"
       - name: Install GHC (GHCup)
         if: matrix.setup-method == 'ghcup'
         run: |
@@ -152,8 +152,9 @@ jobs:
           touch cabal.project
           echo "packages: $GITHUB_WORKSPACE/source/brillo" >> cabal.project
           echo "packages: $GITHUB_WORKSPACE/source/brillo-algorithms" >> cabal.project
-          echo "packages: $GITHUB_WORKSPACE/source/brillo-rendering" >> cabal.project
           echo "packages: $GITHUB_WORKSPACE/source/brillo-examples" >> cabal.project
+          echo "packages: $GITHUB_WORKSPACE/source/brillo-juicy" >> cabal.project
+          echo "packages: $GITHUB_WORKSPACE/source/brillo-rendering" >> cabal.project
           cat cabal.project
       - name: sdist
         run: |
@@ -169,28 +170,33 @@ jobs:
           echo "PKGDIR_brillo=${PKGDIR_brillo}" >> "$GITHUB_ENV"
           PKGDIR_brillo_algorithms="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/brillo-algorithms-[0-9.]*')"
           echo "PKGDIR_brillo_algorithms=${PKGDIR_brillo_algorithms}" >> "$GITHUB_ENV"
-          PKGDIR_brillo_rendering="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/brillo-rendering-[0-9.]*')"
-          echo "PKGDIR_brillo_rendering=${PKGDIR_brillo_rendering}" >> "$GITHUB_ENV"
           PKGDIR_brillo_examples="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/brillo-examples-[0-9.]*')"
           echo "PKGDIR_brillo_examples=${PKGDIR_brillo_examples}" >> "$GITHUB_ENV"
+          PKGDIR_brillo_juicy="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/brillo-juicy-[0-9.]*')"
+          echo "PKGDIR_brillo_juicy=${PKGDIR_brillo_juicy}" >> "$GITHUB_ENV"
+          PKGDIR_brillo_rendering="$(find "$GITHUB_WORKSPACE/unpacked" -maxdepth 1 -type d -regex '.*/brillo-rendering-[0-9.]*')"
+          echo "PKGDIR_brillo_rendering=${PKGDIR_brillo_rendering}" >> "$GITHUB_ENV"
           rm -f cabal.project cabal.project.local
           touch cabal.project
           touch cabal.project.local
           echo "packages: ${PKGDIR_brillo}" >> cabal.project
           echo "packages: ${PKGDIR_brillo_algorithms}" >> cabal.project
-          echo "packages: ${PKGDIR_brillo_rendering}" >> cabal.project
           echo "packages: ${PKGDIR_brillo_examples}" >> cabal.project
+          echo "packages: ${PKGDIR_brillo_juicy}" >> cabal.project
+          echo "packages: ${PKGDIR_brillo_rendering}" >> cabal.project
           echo "package brillo" >> cabal.project
           echo "    ghc-options: -Werror=missing-methods" >> cabal.project
           echo "package brillo-algorithms" >> cabal.project
           echo "    ghc-options: -Werror=missing-methods" >> cabal.project
-          echo "package brillo-rendering" >> cabal.project
-          echo "    ghc-options: -Werror=missing-methods" >> cabal.project
           echo "package brillo-examples" >> cabal.project
+          echo "    ghc-options: -Werror=missing-methods" >> cabal.project
+          echo "package brillo-juicy" >> cabal.project
+          echo "    ghc-options: -Werror=missing-methods" >> cabal.project
+          echo "package brillo-rendering" >> cabal.project
           echo "    ghc-options: -Werror=missing-methods" >> cabal.project
           cat >> cabal.project <<EOF
           EOF
-          $HCPKG list --simple-output --names-only | perl -ne 'for (split /\s+/) { print "constraints: any.$_ installed\n" unless /^(brillo|brillo-algorithms|brillo-examples|brillo-rendering)$/; }' >> cabal.project.local
+          $HCPKG list --simple-output --names-only | perl -ne 'for (split /\s+/) { print "constraints: any.$_ installed\n" unless /^(brillo|brillo-algorithms|brillo-examples|brillo-juicy|brillo-rendering)$/; }' >> cabal.project.local
           cat cabal.project
           cat cabal.project.local
       - name: dump install plan
@@ -219,9 +225,11 @@ jobs:
           ${CABAL} -vnormal check
           cd ${PKGDIR_brillo_algorithms} || false
           ${CABAL} -vnormal check
-          cd ${PKGDIR_brillo_rendering} || false
-          ${CABAL} -vnormal check
           cd ${PKGDIR_brillo_examples} || false
+          ${CABAL} -vnormal check
+          cd ${PKGDIR_brillo_juicy} || false
+          ${CABAL} -vnormal check
+          cd ${PKGDIR_brillo_rendering} || false
           ${CABAL} -vnormal check
       - name: haddock
         run: |
